### ISSUE TITLE
Questioning the README:  Why is RR's Thief Kit Revisions "unnecessary" with M&G?

### ISSUE THREAD

**Issue by agb1** [subtledoctor/Might_and_Guile#3]
I'd like to keep RR's Bounty Hunter and Assassin kit abilities along with M&G's Swashbuckler.

RR component 1 revises Assassin, Swashbuckler and Bounty Hunter kits, modifying abilities as well as THAC0, damage bonuses and backstab multipliers and restricting Swashbucklers from dual-classing to Fighter.

M&G component 420 adds Scout and revises Swashbuckler.  M&G component 120 (Weapon Proficiency Overhaul) modifies the proficiency limits and THAC0.  Does M&G make other changes to the Bounty Hunter and Assassin?  Will M&G 420 fully override RR 1's changes to Swashbuckler if installed after?

**Comment by subtledoctor** [comment]
Hmmm... I think that part of the readme was leftover from the old Scales of Balance 'thief class revisions.'  What you describe above is correct.  The M&G revised swashbuckler uses a totally different CLAB file so it will ignore any changes made by RR.  So you can use RR for Bounty Hunters and Assassins, and use M&G's Swashbuckler.
