### ISSUE TITLE
WPO breaks M#PIRBAN.ITM from Amber NPC mod

### ISSUE THREAD

**Issue by agb1** [subtledoctor/Might_and_Guile#8]
M#PIRBAN.ITM is a "Pirate Bandanna"

It seems WPO deletes the string refs.

Original/modified files here:

http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/?p=584754

**Comment by subtledoctor** [comment]
I'm fairly sure sure my mod doesn't delete string refs.  I don't even know how to delete string refs - I didn't think that was possible.  The WPO uses STRING_SET to alter a few strings, and it uses SET_2DA_ENTRY...RESOLVE_STRREF on a few strings, and it uses SAY NAME1 on some items and spells, and it patches some item descriptions to remove text about usability restrictions.  But none of those operations should "break" an .itm file...
