### ISSUE TITLE
Multiclassed Rogue & Feats

### ISSUE THREAD

**Issue by kelthalas** [subtledoctor/Might_and_Guile#9]
Hi,
I'm currently playing a solo Fighter / Mage / Thief and the level 1 page of my mage spell book is filled with thief feats as seen here http://imgur.com/eCZc4Tw . I can memorize them and cast them. They take up space, preventing me from learning new level 1 spells.

In addition, i'm currently level 11/11/12 and I only have the three starting feats (i took TACH0, backstab and luck). Nothing in my special abilities.

weidu log http://pastebin.com/1aJzXGYm, bg2 ee lastest steam version

**Comment by subtledoctor** [comment]
Will be fixed in the next update, thanks for the heads-up. Meantime, you should just delete those spells from your spellbook.

**Comment by kelthalas** [comment]
Thanks!
I also had random feats in the HLA selection screen (no screenshot i'm at work, but I definitely remember stuff that shouldn't be here like advanced alchemy)

**Comment by subtledoctor** [comment]
Actually, that's intended. With the rogue feats installed, Advanced Alchemy takes the place of the vanilla "Alchemy" HLA.
